name: APP1 Test
on: 
  pull_request:
    paths:
      - 'app1/**'
jobs:
  APP1-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build container image
        run: |
          cd app1
          docker build -t app1 .
