name: APP2 Test
on: 
  pull_request:
    paths:
      - 'app2/**'
jobs:
  APP2-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build container image
        run: |
          cd app2
          docker build -t app2 .

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN_ACTION }}
