name: APP2 Test
on: 
  push:
    paths:
      - 'app2/**'
      - '.github/workflows/app2-test.yml'
jobs:
  APP2-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          output-file: 'app2/CHANGELOG.md'
          version-path: 'app2/version'
          tag-prefix: 'app2-'
          skip-on-empty: 'false'
          skip-version-file: 'true' # ./package.json
          release-count: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Get Version
        id: appVersion
        run: echo "::set-output name=version::$(git tag --sort=-v:refname --list "app2-[0-9]*" | head -n 1 | cut -c 6-)"

      - name: Build and Push to ECR public
        id: build-and-push
        uses: pahud/ecr-public-action@8cd826db40befb59b0cd0b60b22a7ba72d06a7f7
        with:
          dockerfile: .devcontainer/Dockerfile
          context: .devcontainer
          create_repo: ecr_repo_name
          tags: |
            public.ecr.aws/l0y7w6p3/app2:latest
            public.ecr.aws/l0y7w6p3/app2:${{ steps.appVersion.outputs.version }}

      #- name: Build, tag, and push image to Amazon ECR
      #  env:
      #    ECR_REGISTRY: public.ecr.aws/l0y7w6p3
      #    ECR_REPOSITORY: app2
      #  run: |
      #    cd app2
      #    VERSION=$(git tag --sort=-v:refname --list "app2-[0-9]*" | head -n 1 | cut -c 6-)
      #    docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION .
      #    docker push $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION
      #    docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
