name: APP2 Test
on: 
  push:
    paths:
      - 'app2/**'
      - '.github/workflows/app2-test.yml'
jobs:
  APP2-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          output-file: 'app2/CHANGELOG.md'
          version-path: 'app2/version'
          tag-prefix: 'app2-'
          skip-on-empty: 'false'

      - name: Git Version
        run: |
          VERSION=$(git tag --sort=-v:refname --list "app2-[0-9]*" | head -n 1 | cut -c 6-)
          echo "Hola Mundo $VERSION"