name: APP2 Test
on: 
  push:
    paths:
      - 'app2/**'
      - '.github/workflows/app2-test.yml'
jobs:
  APP2-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build container image
        run: |
          cd app2
          docker build -t app2 .

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          tag-prefix: 'app2-'
